package chrome.runtime

typealias ManifestPermissions = String

/** Source: https://developer.chrome.com/docs/extensions/reference/permissions-list */
enum class ManifestPermissionsEnum {
	`accessibilityFeatures.modify`,
	`accessibilityFeatures.read`,
	activeTab,
	alarms,
	audio,
	background,
	bookmarks,
	browsingData,
	certificateProvider,
	clipboardRead,
	clipboardWrite,
	contentSettings,
	contextMenus,
	cookies,
	debugger,
	declarativeContent,
	declarativeNetRequest,
	declarativeNetRequestFeedback,
	declarativeNetRequestWithHostAccess,
	declarativeWebRequest,
	desktopCapture,
	documentScan,
	downloads,
	`downloads.open`,
	`downloads.shelf`,
	`downloads.ui`,
	`enterprise.deviceAttributes`,
	`enterprise.hardwarePlatform`,
	`enterprise.networkingAttributes`,
	`enterprise.platformKeys`,
	experimental,
	favicon,
	fileBrowserHandler,
	fileSystemProvider,
	fontSettings,
	gcm,
	geolocation,
	history,
	identity,
	`identity.email`,
	idle,
	loginState,
	management,
	nativeMessaging,
	notifications,
	offscreen,
	pageCapture,
	platformKeys,
	power,
	printerProvider,
	printing,
	printingMetrics,
	privacy,
	processes,
	proxy,
	readingList,
	scripting,
	search,
	sessions,
	sidePanel,
	storage,
	`system.cpu`,
	`system.display`,
	`system.memory`,
	`system.storage`,
	systemLog,
	tabCapture,
	tabGroups,
	tabs,
	topSites,
	tts,
	ttsEngine,
	unlimitedStorage,
	userScripts,
	vpnProvider,
	wallpaper,
	webAuthenticationProxy,
	webNavigation,
	webRequest,
	webRequestBlocking,
	webRequestAuthProvider,
	;

	val value: ManifestPermissions = name

	companion object {
		fun enumValueOf(value: ManifestPermissions): ManifestPermissionsEnum = valueOf(value)
	}
}

/** Source : https://developer.chrome.com/docs/extensions/reference/api/permissions */
@Suppress("unused")
enum class ManifestOptionalPermissionsEnum {

	`accessibilityFeatures.modify`,
	`accessibilityFeatures.read`,
	activeTab,
	alarms,
	audio,
	background,
	bookmarks,
	browsingData,
	certificateProvider,
	clipboardRead,
	clipboardWrite,
	contentSettings,
	contextMenus,
	cookies,
	declarativeContent,
	declarativeNetRequestFeedback,
	declarativeNetRequestWithHostAccess,
	declarativeWebRequest,
	desktopCapture,
	documentScan,
	downloads,
	`downloads.open`,
	`downloads.shelf`,
	`downloads.ui`,
	`enterprise.deviceAttributes`,
	`enterprise.hardwarePlatform`,
	`enterprise.networkingAttributes`,
	`enterprise.platformKeys`,
	favicon,
	fileBrowserHandler,
	fileSystemProvider,
	gcm,
	history,
	identity,
	`identity.email`,
	idle,
	loginState,
	management,
	nativeMessaging,
	notifications,
	offscreen,
	pageCapture,
	platformKeys,
	power,
	printerProvider,
	printing,
	printingMetrics,
	privacy,
	processes,
	readingList,
	scripting,
	search,
	sessions,
	sidePanel,
	storage,
	`system.cpu`,
	`system.display`,
	`system.memory`,
	`system.storage`,
	systemLog,
	tabCapture,
	tabGroups,
	tabs,
	topSites,
	userScripts,
	vpnProvider,
	webNavigation,
	webRequest,
	webRequestBlocking,
	webRequestAuthProvider,
	;

	val value: ManifestPermissions = name

	companion object {

		fun enumValueOf(value: ManifestPermissions): ManifestPermissionsEnum = ManifestPermissionsEnum.valueOf(value)
	}
}